### ISSUE TITLE
Proper equals and hashCode methods implementation for the domain classes

### ISSUE THREAD

**Issue by maxim-tschumak** [zalando-stups/kio-client-java#13]
**As** a user of the kio-client-java library
**I want** to have proper implementation of the `hashCode` and `equals` methods of the domain classes (e.g. Application)
**So that** I can easily compare the objects (e.g. use them in `Set` constructs)

**Comment by maxim-tschumak** [comment]
If you are OK with using `Lombok` I would implement this improvement and create a PR ;)

**Comment by harti2006** [comment]
What would be your desired strategy to compare Applications? Do you just compare the ids or do all attributes have to match?

**Comment by maxim-tschumak** [comment]
@harti2006 I would prefer to compare all the attributes.

**Comment by harti2006** [comment]
ok, please note that this library has not been touched for while. Most probably it's not up-to-date anymore with the API. There may be some additional fields now that you might consider adding to lib in order to get the complete picture.
